export const COURSE_NAME_TEXTS: string[] = [
    `Compute Architecture`,
    `Design and Analysis of Algorithms`,
    `Principles of Operating Systems`,
    `Structured Programming and Formal Algorithm`,
    `Object Oriented Design`,
    `Machine Learning`,
    `Principles of Social Media & Data Mining`,
    `Blockchain & Cryptocurrencies`,
    `Design Patterns`,
    `Object Oriented Programming with C++`,
    `Compiler Principles`,
    `Distributed Computation`,
    `Computer Vision`,
    `Computer Security`,
    `Social Engineering & Security Penetration`,
];