// Using this brutal method is suprisingly effective than parsing the round number, let's keep it this way.
export const CALENDAR = new Map<number, string>([
    [-1, "Summer - August, Year I"],
    [0, "Fall I - Early September, Year I"],
    [1, "Fall I - Late September, Year I"],
    [2, "Fall I - Early October, Year I"],
    [3, "Fall I - Late October, Year I"],
    [4, "Fall I - Early November, Year I"],
    [5, "Fall I - Late November, Year I"],
    [6, "Fall I - Early December, Year I"],
    [7, "Winter Break - Late December, Year I"],
    [8, "Winter Break - Early January, Year II"],
    [9, "Spring I - Late January, Year II"],
    [10, "Spring I - Early February, Year II"],
    [11, "Spring I - Late February, Year II"],
    [12, "Spring I - Early March, Year II"],
    [13, "Spring I - Late March, Year II"],
    [14, "Spring I - Early April, Year II"],
    [15, "Spring I - Late April, Year II"],
    [16, "Summer Break - Early May, Year II"],
    [17, "Summer Break - Late May, Year II"],
    [18, "Summer Break - Early June, Year II"],
    [19, "Summer Break - Late June, Year II"],
    [20, "Summer Break - Early July, Year II"],
    [21, "Summer Break - Late July, Year II"],
    [22, "Summer Break - Early August, Year II"],
    [23, "Summer Break - Late August, Year II"],
    [24, "Fall II - Early September, Year II"],
    [25, "Fall II - Late September, Year II"],
    [26, "Fall II - Early October, Year II"],
    [27, "Fall II - Late October, Year II"],
    [28, "Fall II - Early November, Year II"],
    [29, "Fall II - Late November, Year II"],
    [30, "Fall II - Early December, Year II"],
    [31, "Winter Break - Late December, Year II"],
    [32, "Winter Break - Early January, Year III"],
    [33, "Spring II - Late January, Year III"],
    [34, "Spring II - Early February, Year III"],
    [35, "Spring II - Late February, Year III"],
    [36, "Spring II - Early March, Year III"],
    [37, "Spring II - Late March, Year III"],
    [38, "Spring II - Early April, Year III"],
    [39, "Spring II - Late April, Year III"],
    [40, "OPT Grace Period - Early May, Year III"],
    [41, "OPT Grace Period - Late May, Year III"],
    [42, "OPT Grace Period - Early June, Year III"],
    [43, "OPT Grace Period - Late June, Year III"],
    [44, "OPT Grace Period - Early July, Year III"],
    [45, "OPT Grace Period - Late July, Year III"],
    [46, "OPT Grace Period - Early August, Year III"],
    [47, "OPT Grace Period - Late August, Year III"],
    [48, "END GAME - September, Year III"]
]);

export function isInVacation(round: number): boolean {
    return CALENDAR.get(round)!.includes("Break") || CALENDAR.get(round)!.includes("OPT");
}