// Using this brutal method is suprisingly effective than parsing the round number, let's keep it this way.
export const CALENDAR = new Map<number, string>([
    [-1, "Summer - August, Y1"],
    [0, "Fall I - Early September, Y1"],
    [1, "Fall I - Late September, Y1"],
    [2, "Fall I - Early October, Y1"],
    [3, "Fall I - Late October, Y1"],
    [4, "Fall I - Early November, Y1"],
    [5, "Fall I - Late November, Y1"],
    [6, "Fall I - Early December, Y1"],
    [7, "Winter Break - Late December, Y1"],
    [8, "Winter Break - Early January, Y2"],
    [9, "Spring I - Late January, Y2"],
    [10, "Spring I - Early February, Y2"],
    [11, "Spring I - Late February, Y2"],
    [12, "Spring I - Early March, Y2"],
    [13, "Spring I - Late March, Y2"],
    [14, "Spring I - Early April, Y2"],
    [15, "Spring I - Late April, Y2"],
    [16, "Summer Break - Early May, Y2"],
    [17, "Summer Break - Late May, Y2"],
    [18, "Summer Break - Early June, Y2"],
    [19, "Summer Break - Late June, Y2"],
    [20, "Summer Break - Early July, Y2"],
    [21, "Summer Break - Late July, Y2"],
    [22, "Summer Break - Early August, Y2"],
    [23, "Summer Break - Late August, Y2"],
    [24, "Fall II - Early September, Y2"],
    [25, "Fall II - Late September, Y2"],
    [26, "Fall II - Early October, Y2"],
    [27, "Fall II - Late October, Y2"],
    [28, "Fall II - Early November, Y2"],
    [29, "Fall II - Late November, Y2"],
    [30, "Fall II - Early December, Y2"],
    [31, "Winter Break - Late December, Y2"],
    [32, "Winter Break - Early January, Y3"],
    [33, "Spring II - Late January, Y3"],
    [34, "Spring II - Early February, Y3"],
    [35, "Spring II - Late February, Y3"],
    [36, "Spring II - Early March, Y3"],
    [37, "Spring II - Late March, Y3"],
    [38, "Spring II - Early April, Y3"],
    [39, "Spring II - Late April, Y3"],
    [40, "Summer Break - Early May, Y3"],
    [41, "Summer Break - Late May, Y3"],
    [42, "Summer Break - Early June, Y3"],
    [43, "Summer Break - Late June, Y3"],
    [44, "Summer Break - Early July, Y3"],
    [45, "Summer Break - Late July, Y3"],
    [46, "Summer Break - Early August, Y3"],
    [47, "Summer Break - Late August, Y3"],
    [48, "END GAME - September, Y3"]
]);

export function isInVacation(round: number): boolean {
    return CALENDAR.get(round)!.includes("Break");
}